# Generated by Django 4.0.3 on 2022-03-14 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etourism_app', '0002_delete_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('departure_Date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('guest', models.IntegerField()),
                ('certificate', models.FileField(upload_to='certificate')),
                ('b_status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etourism_app.login')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etourism_app.package')),
            ],
        ),
    ]
