# Generated by Django 4.0.3 on 2022-03-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etourism_app', '0003_bookings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inquiry',
        ),
    ]
