# Generated by Django 4.0.3 on 2022-03-16 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etourism_app', '0005_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='place_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etourism_app.package')),
            ],
        ),
    ]
