# Generated by Django 4.0.3 on 2022-03-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etourism_app', '0006_place_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='ratting',
            field=models.CharField(max_length=20),
        ),
    ]
