# Generated by Django 4.0.3 on 2022-03-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etourism_app', '0008_rename_name_inquiry_name_rename_phone_inquiry_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='covid_cases',
        ),
        migrations.DeleteModel(
            name='covid_vaccinated_certificate',
        ),
    ]
