# Generated by Django 4.0.3 on 2022-04-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etourism_app', '0009_delete_covid_cases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place_detail',
            name='image',
            field=models.FileField(upload_to='image'),
        ),
    ]
